package lzvn

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// The files testdata/<name>.lzvn were produced on macOS with
// testdata/lzvn-encode.c (libcompression's raw LZVN encoder) from the
// inputs that TestWriteVectorInputs writes (run it with
// LZVN_VECTOR_INPUTS=<dir>). The originals are regenerated by the tests.
var vectors = []struct {
	name string
	gen  func() []byte
}{
	{"eight", func() []byte { return genText(13, 8) }},
	{"text-3k", func() []byte { return genText(11, 3000) }},
	{"text-70k", func() []byte { return genText(3, 70000) }},
	{"random-5k", func() []byte { return genRandom(4, 5000) }},
	{"zeros-100k", func() []byte { return make([]byte, 100000) }},
	{"repeat37-50k", func() []byte { return genRepeat(37, 50000) }},
	{"repeat1000-300k", func() []byte { return genRepeat(1000, 300000) }},
	{"mixed-200k", func() []byte { return genMixed(6, 200000) }},
}

func readVector(t testing.TB, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name+".lzvn"))
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// opcodeKinds walks a well-formed stream and counts its opcode kinds, to
// show which ones the vectors exercise.
func opcodeKinds(src []byte) map[string]int {
	kinds := map[string]int{}
	for s := 0; s < len(src); {
		op := src[s]
		var k string
		var n int
		switch {
		case op == 0x06:
			kinds["eos"]++
			return kinds
		case op == 0x0e || op == 0x16:
			k, n = "nop", 1
		case op == 0xf0:
			k, n = "lrg_m", 2
		case op > 0xf0:
			k, n = "sml_m", 1
		case op == 0xe0:
			k, n = "lrg_l", 2+int(src[s+1])+16
		case op > 0xe0:
			k, n = "sml_l", 1+int(op&15)
		case op >= 0xa0 && op < 0xc0:
			k, n = "med_d", 3+int(op>>3&3)
		case op&7 == 7:
			k, n = "lrg_d", 3+int(op>>6)
		case op&7 == 6:
			k, n = "pre_d", 1+int(op>>6)
		default:
			k, n = "sml_d", 2+int(op>>6)
		}
		kinds[k]++
		s += n
	}
	return kinds
}

func TestVectors(t *testing.T) {
	total := map[string]int{}
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			comp := readVector(t, v.name)
			want := v.gen()
			kinds := opcodeKinds(comp)
			for k, n := range kinds {
				total[k] += n
			}
			t.Logf("%d -> %d bytes, opcodes %v", len(want), len(comp), kinds)

			dst := make([]byte, len(want))
			n, err := Decode(dst, comp)
			if err != nil || n != len(want) || !bytes.Equal(dst, want) {
				t.Fatalf("Decode = %d, %v; output equal: %v", n, err, bytes.Equal(dst[:n], want[:n]))
			}

			// The stream ends with an end-of-stream opcode, so a larger
			// destination yields the same result.
			big := make([]byte, len(want)+100)
			if n, err := Decode(big, comp); err != nil || n != len(want) || !bytes.Equal(big[:n], want) {
				t.Errorf("Decode into larger dst = %d, %v", n, err)
			}

			// Without the end-of-stream opcode and its padding, decoding
			// into an exactly sized destination still succeeds.
			if n, err := Decode(dst, comp[:len(comp)-8]); err != nil || n != len(want) || !bytes.Equal(dst, want) {
				t.Errorf("Decode without trailer = %d, %v", n, err)
			}

			if len(want) > 0 {
				small := make([]byte, len(want)-1)
				if n, err := Decode(small, comp); !errors.Is(err, ErrDstTooSmall) || n > len(small) {
					t.Errorf("Decode into short dst = %d, %v; want ErrDstTooSmall", n, err)
				}
			}
		})
	}
	for _, k := range []string{"sml_d", "med_d", "lrg_d", "pre_d", "sml_m", "lrg_m", "sml_l", "lrg_l", "eos"} {
		if total[k] == 0 {
			t.Errorf("no vector contains a %s opcode", k)
		}
	}
	t.Logf("opcodes over all vectors: %v", total)
}

func TestTruncated(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			comp := readVector(t, v.name)
			want := v.gen()
			dst := make([]byte, len(want))
			step := 1
			if len(comp) > 4096 {
				step = len(comp) / 1999
			}
			for c := 0; c < len(comp); c += step {
				n, err := Decode(dst, comp[:c])
				// A prefix ending on an opcode boundary decodes to a prefix
				// of the original; one ending inside an opcode is corrupt.
				// Either way what was written is correct.
				if err != nil && !errors.Is(err, ErrCorrupt) {
					t.Fatalf("cut at %d: err = %v", c, err)
				}
				if n < 0 || n > len(dst) || !bytes.Equal(dst[:n], want[:n]) {
					t.Fatalf("cut at %d: n = %d, output prefix wrong", c, n)
				}
			}
		})
	}
}

func TestBitFlips(t *testing.T) {
	p := prng(99)
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			orig := readVector(t, v.name)
			want := v.gen()
			dst := make([]byte, len(want))
			comp := make([]byte, len(orig))
			var ok, short, failed int
			for range 500 {
				copy(comp, orig)
				for k := 1 + p.intn(3); k > 0; k-- {
					comp[p.intn(len(comp))] ^= 1 << p.intn(8)
				}
				n, err := Decode(dst, comp)
				if n < 0 || n > len(dst) {
					t.Fatalf("n = %d out of range", n)
				}
				switch {
				case err == nil && n == len(want):
					ok++
				case err == nil:
					// LZVN has no checksums or sizes: a flip can shorten
					// a literal run or match, or turn an opcode into
					// end-of-stream. Callers must compare n with the size
					// they expect.
					short++
				case errors.Is(err, ErrCorrupt) || errors.Is(err, ErrDstTooSmall):
					failed++
				default:
					t.Fatalf("unexpected error %v", err)
				}
			}
			t.Logf("500 trials: %d full length, %d short, %d rejected", ok, short, failed)
		})
	}
}

// TestWriteVectorInputs writes the inputs of the test vectors to the
// directory named by LZVN_VECTOR_INPUTS, for regenerating testdata.
func TestWriteVectorInputs(t *testing.T) {
	dir := os.Getenv("LZVN_VECTOR_INPUTS")
	if dir == "" {
		t.Skip("LZVN_VECTOR_INPUTS not set")
	}
	for _, v := range vectors {
		if err := os.WriteFile(filepath.Join(dir, v.name), v.gen(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}
