package lzfse

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// The files testdata/<name>.lzfse were produced on macOS by
//
//	compression_tool -encode -a lzfse -i <name> -o testdata/<name>.lzfse
//
// from the inputs that TestWriteVectorInputs writes (run it with
// LZFSE_VECTOR_INPUTS=<dir>). The originals are regenerated by the tests.
var vectors = []struct {
	name string
	gen  func() []byte
	// blocks lists the block kinds the vector is known to contain, as a
	// check that the vectors keep exercising what they are meant to.
	blocks string
}{
	{"empty", func() []byte { return nil }, "-$"},
	{"one", func() []byte { return []byte("a") }, "-$"},
	{"seven", func() []byte { return genText(7, 7) }, "-$"},
	{"text-3k", func() []byte { return genText(11, 3000) }, "n$"},
	{"text-4095", func() []byte { return genText(12, 4095) }, "n$"},
	{"text-70k", func() []byte { return genText(3, 70000) }, "22$"},
	{"random-5k", func() []byte { return genRandom(4, 5000) }, "2$"},
	{"random-42k", func() []byte { return genRandom(5, 42000) }, "22$"},
	{"zeros-1m", func() []byte { return make([]byte, 1<<20+3) }, "2$"},
	{"repeat-1m", func() []byte { return genRepeat(37, 1<<20+5) }, "2$"},
	{"mixed-700k", func() []byte { return genMixed(2, 700000) }, "222$"},
}

func readVector(t testing.TB, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name+".lzfse"))
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// blockKinds walks the block structure of a well-formed stream and returns
// one character per block: '-', 'n', '1', '2' or '$'.
func blockKinds(b []byte) string {
	var kinds []byte
	for len(b) >= 4 {
		var h header
		switch le32(b) {
		case magicEOS:
			return string(append(kinds, '$'))
		case magicUncompressed:
			kinds = append(kinds, '-')
			b = b[8+int(le32(b[4:])):]
		case magicLZVN:
			kinds = append(kinds, 'n')
			b = b[12+int(le32(b[8:])):]
		case magicV1, magicV2:
			if le32(b) == magicV1 {
				kinds = append(kinds, '1')
				if h.parseV1(b) != nil {
					return string(kinds) + "?"
				}
			} else {
				kinds = append(kinds, '2')
				if h.parseV2(b) != nil {
					return string(kinds) + "?"
				}
			}
			b = b[h.size+int(h.nLiteralPayloadBytes)+int(h.nLMDPayloadBytes):]
		default:
			return string(kinds) + "?"
		}
	}
	return string(kinds) + "?"
}

func le32(b []byte) uint32 {
	return uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24
}

func TestVectors(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			comp := readVector(t, v.name)
			want := v.gen()
			kinds := blockKinds(comp)
			t.Logf("%d -> %d bytes, blocks %s", len(want), len(comp), kinds)
			if v.blocks != "" && kinds != v.blocks {
				t.Errorf("block kinds %q, want %q", kinds, v.blocks)
			}

			dst := make([]byte, len(want))
			n, err := Decode(dst, comp)
			if err != nil || n != len(want) || !bytes.Equal(dst, want) {
				t.Fatalf("Decode = %d, %v; output equal: %v", n, err, bytes.Equal(dst[:n], want[:n]))
			}

			// A larger destination is fine.
			big := make([]byte, len(want)+100)
			if n, err := Decode(big, comp); err != nil || n != len(want) || !bytes.Equal(big[:n], want) {
				t.Errorf("Decode into larger dst = %d, %v", n, err)
			}

			// A smaller one is not.
			if len(want) > 0 {
				small := make([]byte, len(want)-1)
				if n, err := Decode(small, comp); !errors.Is(err, ErrDstTooSmall) || n > len(small) {
					t.Errorf("Decode into short dst = %d, %v; want ErrDstTooSmall", n, err)
				}
			}
		})
	}
}

// v2ToV1 rewrites every "bvx2" block of a well-formed stream as a "bvx1"
// block with the same payload. Apple's encoder emits only v2 headers, so
// this is how the v1 path is tested.
func v2ToV1(t *testing.T, b []byte) []byte {
	t.Helper()
	var out []byte
	for {
		switch le32(b) {
		case magicEOS:
			return append(out, b[:4]...)
		case magicUncompressed:
			n := 8 + int(le32(b[4:]))
			out, b = append(out, b[:n]...), b[n:]
		case magicLZVN:
			n := 12 + int(le32(b[8:]))
			out, b = append(out, b[:n]...), b[n:]
		case magicV2:
			var h header
			if err := h.parseV2(b); err != nil {
				t.Fatal(err)
			}
			hdr := make([]byte, headerV1Size)
			put32 := func(off int, v uint32) {
				hdr[off], hdr[off+1], hdr[off+2], hdr[off+3] = byte(v), byte(v>>8), byte(v>>16), byte(v>>24)
			}
			put16 := func(off int, v uint16) { hdr[off], hdr[off+1] = byte(v), byte(v>>8) }
			put32(0, magicV1)
			put32(4, h.nRawBytes)
			put32(8, h.nLiteralPayloadBytes+h.nLMDPayloadBytes)
			put32(12, h.nLiterals)
			put32(16, h.nMatches)
			put32(20, h.nLiteralPayloadBytes)
			put32(24, h.nLMDPayloadBytes)
			put32(28, uint32(h.literalBits))
			for i, s := range h.literalState {
				put16(32+2*i, s)
			}
			put32(40, uint32(h.lmdBits))
			put16(44, h.lState)
			put16(46, h.mState)
			put16(48, h.dState)
			for i, f := range h.freq {
				put16(50+2*i, f)
			}
			end := h.size + int(h.nLiteralPayloadBytes) + int(h.nLMDPayloadBytes)
			out = append(out, hdr...)
			out = append(out, b[h.size:end]...)
			b = b[end:]
		default:
			t.Fatalf("unexpected block magic %#x", le32(b))
		}
	}
}

func TestV1Blocks(t *testing.T) {
	for _, v := range vectors {
		comp := readVector(t, v.name)
		if !bytes.Contains([]byte(blockKinds(comp)), []byte("2")) {
			continue
		}
		t.Run(v.name, func(t *testing.T) {
			v1 := v2ToV1(t, comp)
			if k := blockKinds(v1); bytes.Contains([]byte(k), []byte("2")) {
				t.Fatalf("conversion left v2 blocks: %s", k)
			}
			want := v.gen()
			dst := make([]byte, len(want))
			if n, err := Decode(dst, v1); err != nil || n != len(want) || !bytes.Equal(dst, want) {
				t.Fatalf("Decode(v1) = %d, %v", n, err)
			}
		})
	}
}

func TestTruncated(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			comp := readVector(t, v.name)
			want := v.gen()
			dst := make([]byte, len(want))
			step := 1
			if len(comp) > 2048 {
				step = len(comp) / 997
			}
			cuts := []int{}
			for c := 0; c < len(comp); c += step {
				cuts = append(cuts, c)
			}
			for c := max(0, len(comp)-64); c < len(comp); c++ {
				cuts = append(cuts, c)
			}
			for _, c := range cuts {
				n, err := Decode(dst, comp[:c])
				// Without its "bvx$" block every prefix is corrupt, and
				// what was written before the error is still correct.
				if !errors.Is(err, ErrCorrupt) {
					t.Fatalf("cut at %d: err = %v, want ErrCorrupt", c, err)
				}
				if n < 0 || n > len(dst) || !bytes.Equal(dst[:n], want[:n]) {
					t.Fatalf("cut at %d: n = %d, output prefix wrong", c, n)
				}
			}
		})
	}
}

func TestBitFlips(t *testing.T) {
	p := prng(99)
	for _, v := range vectors {
		t.Run(v.name, func(t *testing.T) {
			orig := readVector(t, v.name)
			want := v.gen()
			dst := make([]byte, len(want))
			comp := make([]byte, len(orig))
			trials := 400
			if len(want) > 1<<19 {
				trials = 100
			}
			var ok, failed int
			for range trials {
				copy(comp, orig)
				for k := 1 + p.intn(3); k > 0; k-- {
					i := p.intn(len(comp))
					comp[i] ^= 1 << p.intn(8)
				}
				n, err := Decode(dst, comp)
				if n < 0 || n > len(dst) {
					t.Fatalf("n = %d out of range", n)
				}
				switch {
				case err == nil:
					// Flips in stored bytes or entropy-coded data can
					// decode "successfully"; the block sizes still hold.
					if n != len(want) {
						t.Fatalf("success with %d bytes, want %d", n, len(want))
					}
					ok++
				case errors.Is(err, ErrCorrupt) || errors.Is(err, ErrDstTooSmall):
					failed++
				default:
					t.Fatalf("unexpected error %v", err)
				}
			}
			t.Logf("%d trials: %d decoded, %d rejected", trials, ok, failed)
		})
	}
}

// TestWriteVectorInputs writes the inputs of the test vectors to the
// directory named by LZFSE_VECTOR_INPUTS, for regenerating testdata.
func TestWriteVectorInputs(t *testing.T) {
	dir := os.Getenv("LZFSE_VECTOR_INPUTS")
	if dir == "" {
		t.Skip("LZFSE_VECTOR_INPUTS not set")
	}
	for _, v := range vectors {
		if err := os.WriteFile(filepath.Join(dir, v.name), v.gen(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}
