package hfsplus

// HFS+ catalog names.
//
// A catalog key holds a name as up to 255 UTF-16 units. What macOS stores is
// not the POSIX name it was given: the kernel's HFS+ code converts the UTF-8
// component to UTF-16, swaps ':' and '/', decomposes every character with
// Apple's own decomposition table (Unicode 3.2 canonical decompositions minus
// U+2000-U+2FFF, U+F900-U+FAFF and everything outside the BMP), puts runs of
// combining marks into canonical order (by Unicode 3.2 classes; marks outside
// the BMP count as class 0), maps U+2400 to a stored NUL and
// escapes the noncharacters it considers illegal as "%XX" bytes. Names are
// compared with FastUnicodeCompare (case-insensitive, TN1150) on HFS+ and
// with a binary compare on case-sensitive HFSX.
//
// The tables in unicode_tables.go are generated by internal/gen/unicode from
// Unicode 3.2 data and checked against, and corrected by, measurements of the
// macOS kernel; see that file's header.

import (
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"
)

// errInvalidName is wrapped by every error nameToHFS returns.
var errInvalidName = errors.New("hfsplus: invalid name")

// maxNameUnits is the longest name a catalog key holds (HFSUniStr255).
const maxNameUnits = 255

// Hangul syllables decompose algorithmically (Unicode 3.2 section 3.12).
const (
	hangulSBase  = 0xAC00
	hangulLBase  = 0x1100
	hangulVBase  = 0x1161
	hangulTBase  = 0x11A7
	hangulTCount = 28
	hangulNCount = 21 * hangulTCount
	hangulSCount = 19 * hangulNCount
)

// nameToHFS converts one POSIX path component (UTF-8) to the stored HFS+ form:
// ':' -> '/', Apple decomposition, canonical reordering of combining marks, UTF-16 (surrogate pairs for >BMP).
// Returns an error (wrapping errInvalidName) for invalid UTF-8, names containing '/' or NUL, empty names, or results longer than 255 UTF-16 units.
//
// Two further conversions mirror the kernel: U+2400 SYMBOL FOR NULL becomes a
// stored NUL (it is how the kernel spells the NULs of the private metadata
// directory), and the characters the kernel rejects as illegal, the
// noncharacters listed in escapedRunes, are stored as their UTF-8 bytes
// escaped as "%XX" -- the name readdir then shows. The kernel escapes invalid
// UTF-8 the same way; this function returns an error instead.
func nameToHFS(s string) ([]uint16, error) {
	if s == "" {
		return nil, fmt.Errorf("%w: empty name", errInvalidName)
	}
	out := make([]uint16, 0, len(s))
	marks := false
	for i := 0; i < len(s); {
		if len(out) > maxNameUnits {
			break
		}
		c := s[i]
		if c < utf8.RuneSelf {
			switch c {
			case 0:
				return nil, fmt.Errorf("%w: %q contains NUL", errInvalidName, s)
			case '/':
				return nil, fmt.Errorf("%w: %q contains '/'", errInvalidName, s)
			case ':':
				c = '/'
			}
			out = append(out, uint16(c))
			i++
			continue
		}
		r, n := utf8.DecodeRuneInString(s[i:])
		if r == utf8.RuneError && n == 1 {
			return nil, fmt.Errorf("%w: %q is not valid UTF-8", errInvalidName, s)
		}
		switch {
		case r == 0x2400:
			out = append(out, 0)
		case r >= hangulSBase && r < hangulSBase+hangulSCount:
			x := r - hangulSBase
			out = append(out, uint16(hangulLBase+x/hangulNCount), uint16(hangulVBase+x%hangulNCount/hangulTCount))
			if t := x % hangulTCount; t != 0 {
				out = append(out, uint16(hangulTBase+t))
			}
		case isEscapedRune(r):
			for _, b := range []byte(s[i : i+n]) {
				out = append(out, '%', uint16(hexDigits[b>>4]), uint16(hexDigits[b&15]))
			}
		case r > 0xFFFF:
			r -= 0x10000
			out = append(out, uint16(0xD800+r>>10), uint16(0xDC00+r&0x3FF))
		default:
			if d, ok := decompose(uint16(r)); ok {
				out = append(out, d...)
			} else {
				out = append(out, uint16(r))
			}
			marks = true
		}
		i += n
	}
	if len(out) > maxNameUnits {
		return nil, fmt.Errorf("%w: %q is longer than %d UTF-16 units when decomposed", errInvalidName, s, maxNameUnits)
	}
	if marks {
		canonicalOrder(out)
	}
	return out, nil
}

const hexDigits = "0123456789ABCDEF"

// decompose returns the stored (fully decomposed, canonically ordered) form of
// a BMP code point other than a Hangul syllable, if it has one.
func decompose(c uint16) ([]uint16, bool) {
	if c < decompKeys[0] {
		return nil, false
	}
	lo, hi := 0, len(decompKeys)
	for lo < hi {
		m := int(uint(lo+hi) >> 1)
		if decompKeys[m] < c {
			lo = m + 1
		} else {
			hi = m
		}
	}
	if lo == len(decompKeys) || decompKeys[lo] != c {
		return nil, false
	}
	return decompData[decompStart[lo]:decompStart[lo+1]], true
}

// isEscapedRune reports whether the kernel stores r percent-escaped.
func isEscapedRune(r rune) bool {
	if r < escapedRunes[0] {
		return false
	}
	for _, e := range escapedRunes {
		if e == r {
			return true
		}
	}
	return false
}

// combiningClass is the canonical combining class the kernel uses for a unit.
func combiningClass(c uint16) uint8 {
	if p := cccIndex[c>>8]; p != 0 {
		return cccPages[int(p-1)<<8|int(c&0xFF)]
	}
	return 0
}

// canonicalOrder sorts each run of units with a non-zero combining class by
// class, stably (the Unicode canonical ordering algorithm).
func canonicalOrder(u []uint16) {
	for i := 1; i < len(u); i++ {
		c := combiningClass(u[i])
		if c == 0 {
			continue
		}
		j := i
		for j > 0 && combiningClass(u[j-1]) > c {
			u[j], u[j-1] = u[j-1], u[j]
			j--
		}
	}
}

// nameFromHFS converts a stored name to the POSIX form presented by the macOS VFS:
// '/' -> ':', NUL -> U+2400, UTF-16 -> UTF-8 (unpaired surrogates -> U+FFFD). No recomposition.
//
// A stored ':' reads as ':' as well, as it does on macOS. For names the kernel
// never writes itself readdir on macOS differs by design: it passes unpaired
// surrogates through as their 3-byte (invalid UTF-8) encodings and drops
// U+FFFE and U+FFFF, where nameFromHFS writes U+FFFD and keeps them.
func nameFromHFS(u []uint16) string {
	// Bound the result's size so it is built with a single allocation.
	n := 0
	for _, c := range u {
		switch {
		case c == 0:
			n += 3 // U+2400
		case c < 0x80:
			n++
		case c < 0x800:
			n += 2
		default:
			n += 3 // at most: a surrogate pair takes 4 bytes for 2 units, U+FFFD 3
		}
	}
	var b strings.Builder
	b.Grow(n)
	for i := 0; i < len(u); i++ {
		c := u[i]
		switch {
		case c == '/':
			b.WriteByte(':')
		case c == 0:
			b.WriteString("\u2400")
		case c < utf8.RuneSelf:
			b.WriteByte(byte(c))
		case c >= 0xD800 && c < 0xDC00 && i+1 < len(u) && u[i+1] >= 0xDC00 && u[i+1] < 0xE000:
			b.WriteRune(0x10000 + (rune(c)-0xD800)<<10 + rune(u[i+1]) - 0xDC00)
			i++
		case c >= 0xD800 && c < 0xE000:
			b.WriteRune(utf8.RuneError)
		default:
			b.WriteRune(rune(c))
		}
	}
	return b.String()
}

// foldUnit is gLowerCaseTable: the case-folded value of a unit, 0 if it is
// ignored by the comparison.
func foldUnit(c uint16) uint16 {
	if p := foldIndex[c>>8]; p != 0 {
		return foldPages[int(p-1)<<8|int(c&0xFF)]
	}
	return c
}

// compareFold is FastUnicodeCompare: <0, 0, >0.
func compareFold(a, b []uint16) int {
	i, j := 0, 0
	for {
		var c1, c2 uint16
		for c1 == 0 && i < len(a) {
			c1 = foldUnit(a[i])
			i++
		}
		for c2 == 0 && j < len(b) {
			c2 = foldUnit(b[j])
			j++
		}
		if c1 != c2 {
			if c1 < c2 {
				return -1
			}
			return 1
		}
		if c1 == 0 {
			return 0
		}
	}
}

// compareBinary is HFSX binary comparison of UTF-16 units: <0, 0, >0.
func compareBinary(a, b []uint16) int {
	n := min(len(a), len(b))
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			if a[i] < b[i] {
				return -1
			}
			return 1
		}
	}
	switch {
	case len(a) < len(b):
		return -1
	case len(a) > len(b):
		return 1
	}
	return 0
}
